version: '3'

services:
    
    httpd-front:
        image: maximatt/httpd-front
        hostname: httpd-front.maximatt.org
        ports:
            - 80:80
        networks:
            maximattNet:
                ipv4_address: 172.30.0.101
        depends_on:
            - trac
            - git
        links:
            - "trac:trac.maximatt.org"
            - "git:git.maximatt.org"
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./httpd/config/proxy.conf:/etc/httpd/conf.d/proxy.conf

    trac:
        image: maximatt/trac
        ports:
            - 5002:80
        networks:
            maximattNet:
                ipv4_address: 172.30.0.102
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./trac-repository:/home/trac/repository
        environment:
            TRAC_USER: tuser
            TRAC_PASS: tpass

    git:
        image: maximatt/git
        hostname: git.maximatt.org
        ports:
            - 5003:80
        networks:
            maximattNet:
                ipv4_address: 172.30.0.103
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./git-repository:/home/git
        environment:
            GIT_USER: guser
            GIT_PASS: gpass
            GIT_NAME: maximatt
            GIT_EMAIL: azamax@gmail.com

    svn:
        image: maximatt/svn
        hostname: svn.maximatt.org
        ports:
            - 5004:80
        networks:
            maximattNet:
                ipv4_address: 172.30.0.104
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./svn-repository:/home/svn
        environment:
            SVN_USER: suser
            SVN_PASS: spass
            
    registry:
        hostname: registry.maximatt.org
        container_name: registry
        image: registry
        environment:  
            REGISTRY_HTTP_ADDR: "172.28.0.105:443"
            REGISTRY_HTTP_SECRET: secret
            REGISTRY_HTTP_TLS_CERTIFICATE: /certs/cert.crt
            REGISTRY_HTTP_TLS_KEY: /certs/cert.key
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd 
        ports:
            - 443:443
        networks:
            maximatt-dev:
                ipv4_address: 172.28.0.105
        tmpfs:
            - /run
            - /tmp
        volumes:
            - registry-data:/var/lib/registry
            - ./registry/certs:/certs
            - ./registry/auth:/auth

volumes:
  registry-data:
  
networks:
  maximattNet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
