version: '3'

services:
    
    httpd-front:
        image: maximatt/httpd-front
        hostname: httpd-front.maximatt.org
        ports:
            - 80:80
        networks:
            maximattNet:
                ipv4_address: 172.30.0.101
        depends_on:
            - trac
            - git
        links:
            - "trac:trac.maximatt.org"
            - "git:git.maximatt.org"
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./httpd/config/proxy.conf:/etc/httpd/conf.d/proxy.conf

    trac:
        image: maximatt/trac
        ports:
            - 5002:80
        networks:
            maximattNet:
                ipv4_address: 172.30.0.102
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./trac-repository:/home/trac/repository
        environment:
            TRAC_USER: tuser
            TRAC_PASS: tpass

    git:
        image: maximatt/git
        hostname: git.maximatt.org
        ports:
            - 5003:80
        networks:
            maximattNet:
                ipv4_address: 172.30.0.103
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./git-repository:/home/git
        environment:
            GIT_USER: guser
            GIT_PASS: gpass
            GIT_NAME: maximatt
            GIT_EMAIL: azamax@gmail.com
  
networks:
  maximattNet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
