version: '3'

services:
    centos7-base:
        build:
            context: ./base
        image: centos7-base
        hostname: base.maximatt.org
        container_name: centos7-base
        networks:
            maximatt-net:
                ipv4_address: 172.28.0.100
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro

    httpd-front:
        build:
            context: ./httpd
        image: httpd-front
        hostname: httpd-front.maximatt.org
        container_name: httpd-front
        ports:
            - 80:80
        networks:
            maximatt-net:
                ipv4_address: 172.28.0.101
        depends_on:
            - trac
            - git
        links:
            - "trac:trac.maximatt.org"
            - "git:git.maximatt.org"
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./httpd/config/proxy.conf:/etc/httpd/conf.d/proxy.conf

    trac:
        build:
            context: ./trac
            args:
              - TRAC_PORT=5002
        image: trac
        hostname: trac.maximatt.org
        container_name: trac
        ports:
            - 5002:80
        networks:
            maximatt-net:
                ipv4_address: 172.28.0.102
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./trac/repository:/home/trac/repository
        environment:
            TRAC_USER: tuser
            TRAC_PASS: tpass

    git:
        build:
            context: ./git
            args:
              - GIT_SERVER=git.maximatt.org
              - GIT_PORT=5003
        hostname: git.maximatt.org
        container_name: git
        image: git
        ports:
            - 5003:80
        networks:
            maximatt-net:
                ipv4_address: 172.28.0.103
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./git/repository:/home/git
        environment:
            GIT_USER: guser
            GIT_PASS: gpass
            GIT_NAME: maximatt
            GIT_EMAIL: azamax@gmail.com
            
networks:
  maximatt-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
