version: '3.3'

services:
    tor-service:
        image: maximatt/tor-service
        hostname: tor.service.anonymous.org
        networks:
            tor-net:
                ipv4_address: 172.172.0.171
        ports:
            - 80:80
        depends_on:
            - tor-site
        links:
            - tor-site
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro

    tor-site:
        image: nginx
        networks:
            tor-net:
                ipv4_address: 172.172.0.172
        ports:
          - 8080:80

networks:
  tor-net:
    ipam:
      driver: default
      config:
        - subnet: 172.172.0.0/24
